gText_Birch_Welcome::
	.string "…Hey, wake up!\n"
	.string "Did you hit your head or something?\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is JON BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON”.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "sometimes as friendly playmates,\l"
	.string "while others use them for unpaid labour.\p"
	.string "And sometimes, we join forces\n"
	.string "and battle others.\p"
	.string "Despite our closeness, there's still a\n"
	.string "lot we don't know about POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But that's enough about me.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy or a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ohhh!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I completely forgot you were coming!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "friendships, and eco-terrorists await!\p"
	.string "Come see me in my POKéMON LAB if you\n"
	.string "want some WEED.\p"
	.string "Trust me, kid, you'll need it.\p"
	.string "$"
