FortreeCity_House5_MapScripts::
	.byte 0

Chillage_House5_EventScript_PokefanF::
	msgbox Chillage_House5_Text_TreeHousesAreGreat, MSGBOX_NPC
	end

Chillage_House5_EventScript_Man::
	msgbox Chillage_House5_Text_Incredible, MSGBOX_NPC
	end

Chillage_House5_EventScript_Sourtot::
	msgbox Chillage_House5_Text_Sourtot, MSGBOX_NPC
	end

Chillage_House5_Text_TreeHousesAreGreat:
	.string "These tree houses are great!\p"
	.string "I'd live in the CHILLAGE, if it weren't\n"
	.string "for their draconian rules.$"

Chillage_House5_Text_Incredible:
	.string "Incredible!\p"
	.string "Who knew POKéMON could learn how to run\n"
	.string "their own civilisations, let alone human\l"
	.string "speech.$"

Chillage_House5_Text_Sourtot:
	.string "SOURTOT: Ouuugh…\p"
	.string "Why are there so many tourists\n"
	.string "here lately?$"

